// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThphxYojLn75lSjP-xkEQhKl46PVQ8-k',
    appId: '1:712463742911:android:54a4c1213e887d77e6130a',
    messagingSenderId: '712463742911',
    projectId: 'meditrack-81c24',
    storageBucket: 'meditrack-81c24.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCymUEQYB4wsk2r_UQoXnk4Hf-90WQC05A',
    appId: '1:712463742911:web:43a9152674213e59e6130a',
    messagingSenderId: '712463742911',
    projectId: 'meditrack-81c24',
    authDomain: 'meditrack-81c24.firebaseapp.com',
    storageBucket: 'meditrack-81c24.firebasestorage.app',
    measurementId: 'G-FKFFBL13XH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKkVilDSsweXW2pAJueZisOnO_fXvFR4',
    appId: '1:712463742911:ios:8983672c289ce38fe6130a',
    messagingSenderId: '712463742911',
    projectId: 'meditrack-81c24',
    storageBucket: 'meditrack-81c24.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKkVilDSsweXW2pAJueZisOnO_fXvFR4',
    appId: '1:712463742911:ios:9d6d73c9974137e0e6130a',
    messagingSenderId: '712463742911',
    projectId: 'meditrack-81c24',
    storageBucket: 'meditrack-81c24.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCymUEQYB4wsk2r_UQoXnk4Hf-90WQC05A',
    appId: '1:712463742911:web:8ec7daa45db92bf3e6130a',
    messagingSenderId: '712463742911',
    projectId: 'meditrack-81c24',
    authDomain: 'meditrack-81c24.firebaseapp.com',
    storageBucket: 'meditrack-81c24.firebasestorage.app',
    measurementId: 'G-E170VCH41S',
  );

}